# Generated by Django 2.2.1 on 2019-05-28 06:39

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户昵称')),
                ('avatar', models.FileField(upload_to='avatar/', verbose_name='用户头像')),
                ('mobile', models.CharField(blank=True, max_length=13, null=True, verbose_name='手机号')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=1, null=True, verbose_name='用户性别')),
                ('subscribe', models.BooleanField(default=False, verbose_name='是否订阅')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'my_user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
